
from PyQt6 import QtCore, QtGui, QtWidgets


class Vhod(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 331)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 70, 139, 99))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Password = QtWidgets.QLabel(self.layoutWidget)
        self.Password.setObjectName("Password")
        self.gridLayout.addWidget(self.Password, 3, 0, 1, 1)
        self.Pass_vod = QtWidgets.QLineEdit(self.layoutWidget)
        self.Pass_vod.setObjectName("Pass_vod")
        self.gridLayout.addWidget(self.Pass_vod, 4, 0, 1, 1)
        self.Email_Vod = QtWidgets.QLineEdit(self.layoutWidget)
        self.Email_Vod.setObjectName("Email_Vod")
        self.gridLayout.addWidget(self.Email_Vod, 1, 0, 1, 1)
        self.Email = QtWidgets.QLabel(self.layoutWidget)
        self.Email.setObjectName("Email")
        self.gridLayout.addWidget(self.Email, 0, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 200, 195, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Vhod = QtWidgets.QPushButton(self.layoutWidget1)
        self.Vhod.setObjectName("Vhod")
        self.gridLayout_2.addWidget(self.Vhod, 0, 0, 1, 1)
        self.Register = QtWidgets.QPushButton(self.layoutWidget1)
        self.Register.setObjectName("Register")
        self.gridLayout_2.addWidget(self.Register, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 30, 141, 211))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("75c4629c08b738616179d38041032b1e.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "В х о д"))
        self.Password.setText(_translate("MainWindow", "Password"))
        self.Email.setText(_translate("MainWindow", "Email"))
        self.Vhod.setText(_translate("MainWindow", "Вход"))
        self.Register.setText(_translate("MainWindow", "Регистрация"))
