from PyQt6 import QtCore, QtGui, QtWidgets


class Register(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 413)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)

        self.label.setGeometry(QtCore.QRect(180, 20, 271, 21))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Name_reg = QtWidgets.QLabel(self.centralwidget)
        self.Name_reg.setGeometry(QtCore.QRect(500, 50, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Name_reg.setFont(font)
        self.Name_reg.setObjectName("Name_reg")
        self.Name_vod_reg = QtWidgets.QLineEdit(self.centralwidget)
        self.Name_vod_reg.setGeometry(QtCore.QRect(480, 100, 113, 20))
        self.Name_vod_reg.setObjectName("Name_vod_reg")
        self.Email_reg = QtWidgets.QLabel(self.centralwidget)
        self.Email_reg.setGeometry(QtCore.QRect(500, 130, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Email_reg.setFont(font)
        self.Email_reg.setObjectName("Email_reg")
        self.Email_vod_reg = QtWidgets.QLineEdit(self.centralwidget)
        self.Email_vod_reg.setGeometry(QtCore.QRect(480, 180, 113, 20))
        self.Email_vod_reg.setObjectName("Email_vod_reg")
        self.Pass_reg = QtWidgets.QLabel(self.centralwidget)
        self.Pass_reg.setGeometry(QtCore.QRect(480, 210, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Pass_reg.setFont(font)
        self.Pass_reg.setObjectName("Pass_reg")
        self.Pass_vod = QtWidgets.QLineEdit(self.centralwidget)
        self.Pass_vod.setGeometry(QtCore.QRect(480, 240, 113, 20))
        self.Pass_vod.setObjectName("Pass_vod")
        self.Zaregistr = QtWidgets.QPushButton(self.centralwidget)
        self.Zaregistr.setEnabled(True)
        self.Zaregistr.setGeometry(QtCore.QRect(110, 90, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yi Baiti")
        self.Zaregistr.setFont(font)
        self.Zaregistr.setObjectName("Zaregistr")
        self.Vyhod = QtWidgets.QPushButton(self.centralwidget)
        self.Vyhod.setGeometry(QtCore.QRect(110, 130, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yi Baiti")
        self.Vyhod.setFont(font)
        self.Vyhod.setObjectName("Vyhod")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 210, 411, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("37315cb6e436fd66c398033cc487bb7a.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 644, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Регистрация"))
        self.Name_reg.setText(_translate("MainWindow", "Name"))
        self.Email_reg.setText(_translate("MainWindow", "Email"))
        self.Pass_reg.setText(_translate("MainWindow", "Password"))
        self.Zaregistr.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.Vyhod.setText(_translate("MainWindow", "Выход"))
